[package]
name = "personal"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.9.0"
env_logger = "0.11.6"
serde = "1.0.218"
serde_json = "1.0.139"
tera = "1.20.0"
