services:
  web:
    container_name: namish-personal-website
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4321:8080"
    environment:
      - ENVIRONMENT=PRODUCTION
    restart: unless-stopped
