services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personal
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: Cargo.toml
        - action: sync+restart
          path: ./content
          target: /app/content
        - action: sync+restart
          path: ./templates
          target: /app/templates
        - action: sync+restart
          path: ./static
          target: /app/static
    environment:
      - RUST_LOG=info
    restart: unless-stopped