services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=PRODUCTION
    volumes:
      # Optional: Persist content and static files
      - ./content:/app/content
      - ./static:/app/static
      - ./templates:/app/templates
    restart: unless-stopped
