services:
  web:
    container_name: namish-personal-website
    image: ghcr.io/namishh/me:latest
    ports:
      - "4321:8080"
    environment:
      - ENVIRONMENT=PRODUCTION
    restart: unless-stopped
